#!/bin/sh
#
# Startup script for the edna mp3 mini server 
#
# chkconfig:2345 97 97
# description: edna is a mini mp3 webserver 
#
# processname: python
# pidfile: /var/run/ednad.pid
# config: 

# Source function library.

EDNA=/usr/bin/edna
EDNAD=/usr/bin/ednad
initdir=/etc/init.d
pidfile=/var/run/ednad.pid
EDNACONF=/etc/edna/edna.conf

PYTHONPATH=/usr/lib/edna
export PYTHONPATH
#
# Determine which kind of configuration we're using
#
system=unknown
if [ -f /etc/debian_version ]; then
    system=debian
elif [ -f /etc/redhat-release ]; then
    system=redhat
else
    echo "$0: Unknown system, please port" 1>&2
    exit 1
fi

if [ $system = redhat ]; then
    . $initdir/functions
fi


[ -f $EDNA ] || exit 0


RETVAL=0

function redhat () {
    case "$1" in
    start)
        echo -n "Starting ednad: "
        daemon ${EDNAD}
        echo
        touch /var/lock/subsys/ednad
        return $RETVAL
        ;;
    stop)
        echo -n "Shutting down ednad: "
        EDNADPID=
        EDNADPID=$(cat $pidfile)
        kill $EDNADPID
        echo
        rm -f /var/lock/subsys/ednad $pidfile
        return $RETVAL
        ;;
    status)
        EDNADPID=
        EDNADPID=$(cat $pidfile)
        echo -n "Checking for ednad, PID is : " $EDNADPID
        echo 
         ;;
    restart)
         stop
         start
         ;;
    *)
        echo "Usage: $0 {start | stop | restart | status}"
	exit 1
    esac
}

function debian () {
case "$1" in
    start)
	echo -n 'Starting edna mp3 server: edna'
	start-stop-daemon --start --quiet -pidfile --pidfile $pidfile  --exec $EDNA -- --daemon $EDNACONF
        echo "."
        ;;

    stop)
	echo -n 'Stopping edna mp3 server: edna'
	start-stop-daemon --stop --quiet --oknodo --pidfile $pidfile --exec $EDNA
        echo "."
	;;

    reload)
        start-stop-deamon --stop --signal 1 --oknodo --pidfile $pidfile --exec $EDNA
        ;;


  restart)
	echo -n 'Restarting edna mp3 server: edna'
	start-stop-daemon --stop --quiet --oknodo --pidfile $pidfile --exec $EDNA
	sleep 10
	start-stop-daemon --start --quiet --pidfile $pidfile --exec $EDNA -- --daemon $EDNACONF
	echo "."
	;;

  *)
	echo "Usage: /etc/init.d/edna {start|stop|reload|restart}"
	exit 1
esac
}

if [ $system = debian ]; then
	debian "$@"
elif [ $system = redhat ]; then
	redhat "$@"
fi


exit 0
